version: '3'
services:
  wol:
    image: janpluskal/go-rest-wol
    build: . 
    ports:
      - "8080:8080"
    environment:
      - "WOLFILE=/config/computer.csv"
    volumes:
      - "./config:/config"
